# Generated by Django 4.2.23 on 2025-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='student', max_length=10)),
                ('l_name', models.CharField(default='student', max_length=10)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('statust', models.BooleanField()),
                ('reporet', models.TextField(max_length=300)),
            ],
        ),
    ]
